name: Member Profile Generation
on:
  push:
    branches:
      - main
    paths:
      - "data/member_profiles.yaml"
      - "tools/thinkio_webtool/misc/manualRun.txt"
defaults:
  run:
    working-directory: "./tools/thinkio_webtool"
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.7
    - name: install dependencies
      run: dart pub get
    - name: generate
      run: dart run bin/member_gen.dart